### ISSUE TITLE
Support hiding of <Col>s on specific breakpoints.

### ISSUE THREAD

**Issue by joeruello** [aaronvanston/react-flexa#63]
Would be great if we could hide Columns on various breakpoints.

Either by something like
`<Col xs={0} md={6}>`

or even more explicit:
`<Col xs={'hidden'} md={6}>`

Happy to work on a PR if this is something you guys would be open too.

**Comment by aaronvanston** [comment]
@joeruello Looks good! More than happy to support this syntax (even both options could be implemented), if you want to give a PR a crack that would help out heaps! If not I can try get something through this weekend if I get a chance. 

Should be relatively straightforward. within the gutter width helper function, check if `0` or `"hidden"` and then return `display: none`.

**Comment by aaronvanston** [comment]
closed with #64 and released with v0.5.0
