### ISSUE TITLE
In Col component, display prop is not working as expected

### ISSUE THREAD

**Issue by rohithart** [aaronvanston/react-flexa#83]
`<Col xs={6 } display={{ xs: 'block', sm: 'block', md: 'block', lg: 'none' }} className={styles.col}>`

Output HTML is 
`<div class="Contacts__col___1nJPK sc-VigVT kFVPDi" display="[object Object]"></div>`

**Comment by aaronvanston** [comment]
Hi @rohithart,

Thanks for submitting an issue. Can you provide a little more information? What is your expected outcome and what is it actually doing?

It looks like from the generated HTML that the display prop is not being transformed correctly, can you confirm what version you are using and show me the whole code, import statement, row etc.

**Comment by rohithart** [comment]
Sorry My bad. Thanks @aaronvanston
